export const sample_cards = [
  {
    content: "1",
    type: "1",
    valueNumber: 1,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "1",
    type: "1",
    valueNumber: 1,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "1",
    type: "1",
    valueNumber: 1,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "1",
    type: "1",
    valueNumber: 1,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "2",
    type: "2",
    valueNumber: 2,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "2",
    type: "2",
    valueNumber: 2,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "2",
    type: "2",
    valueNumber: 2,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "2",
    type: "2",
    valueNumber: 2,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },

  {
    content: "3",
    type: "3",
    valueNumber: 3,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "3",
    type: "3",
    valueNumber: 3,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "3",
    type: "3",
    valueNumber: 3,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "3",
    type: "3",
    valueNumber: 3,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },

  {
    content: "4",
    type: "4",
    valueNumber: 4,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "4",
    type: "4",
    valueNumber: 4,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "4",
    type: "4",
    valueNumber: 4,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "4",
    type: "4",
    valueNumber: 4,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },

  {
    content: "5",
    type: "5",
    valueNumber: 5,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "5",
    type: "5",
    valueNumber: 5,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "5",
    type: "5",
    valueNumber: 5,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "5",
    type: "5",
    valueNumber: 5,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },

  {
    content: "6",
    type: "6",
    valueNumber: 6,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "6",
    type: "6",
    valueNumber: 6,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "6",
    type: "6",
    valueNumber: 6,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "6",
    type: "6",
    valueNumber: 6,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },

  {
    content: "7",
    type: "7",
    valueNumber: 7,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "7",
    type: "7",
    valueNumber: 7,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "7",
    type: "7",
    valueNumber: 7,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "7",
    type: "7",
    valueNumber: 7,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },

  {
    content: "8",
    type: "8",
    valueNumber: 8,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "8",
    type: "8",
    valueNumber: 8,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "8",
    type: "8",
    valueNumber: 8,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "8",
    type: "8",
    valueNumber: 8,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },

  {
    content: "9",
    type: "9",
    valueNumber: 9,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "9",
    type: "9",
    valueNumber: 9,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "9",
    type: "9",
    valueNumber: 9,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "9",
    type: "9",
    valueNumber: 9,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },

  {
    content: "10",
    type: "10",
    valueNumber: 10,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "10",
    type: "10",
    valueNumber: 10,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "10",
    type: "10",
    valueNumber: 10,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "10",
    type: "10",
    valueNumber: 10,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "+20",
    type: "20",
    valueNumber: 20,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "+20",
    type: "20",
    valueNumber: 20,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "+20",
    type: "20",
    valueNumber: 20,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "+20",
    type: "20",
    valueNumber: 20,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "-1",
    type: "minusOne",
    valueNumber: -1,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "25",
    type: "25",
    valueNumber: 25,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "25",
    type: "25",
    valueNumber: 25,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },

  {
    content: "0",
    type: "0",
    valueNumber: 0,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "0",
    type: "0",
    valueNumber: 0,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },

  {
    content: "Take and give",
    type: "takeAndGive",
    valueNumber: 10,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "Take and give",
    type: "takeAndGive",
    valueNumber: 10,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "Take and give",
    type: "takeAndGive",
    valueNumber: 10,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "Take and give",
    type: "takeAndGive",
    valueNumber: 10,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },

  {
    content: "circular",
    type: "circular",
    valueNumber: 10,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "circular",
    type: "circular",
    valueNumber: 10,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "Basra",
    type: "Basra",
    valueNumber: 10,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
  {
    content: "Basra",
    type: "Basra",
    valueNumber: 10,
    changed: false,
    imageUrl: "assets/Mirror_Logo.png",
  },
];
